FROM nginx:1.17
MAINTAINER Mathieu Dugre <mail@mdugre.info>

ENV APP_BUNDLE_DIR=/opt/nginx/dist \
    APP_HTML_SRC=/opt/nginx/dist/html

# COPY . $APP_SOURCE_DIR

EXPOSE 80
EXPOSE 443

VOLUME /etc/nginx/conf.d
VOLUME /usr/share/nginx/html

CMD ["/opt/nginx/dist/run.sh"]

# Copier contenu static et react dans l'image
COPY static/html $APP_HTML_SRC
COPY react_build/build/ $APP_HTML_SRC/react

RUN $APP_SOURCE_DIR/scripts/setup.sh && \
    rm -rf $APP_SOURCE_DIR

WORKDIR $APP_BUNDLE_DIR
